language: cpp
os:
  - linux
complier:
  - gcc
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty

    packages:
      - cppcheck
      - make
      - cmake
      - clang-format-10
script:
  #- gcc -g -Wall -Wextra -Werror test2.c -o demo
  - then cppcheck --error-exitcode=1 test2.c ; fi
  - then cppcheck --version ; fi
  - clang-format-10 --dry-run -Werror test2.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
